### ISSUE TITLE
使用fc_clip生成superpixel时输出图片为全黑是怎么回事？

### ISSUE THREAD

**Issue by Gmonster-24** [sbysbysbys/UOV#2]
感谢作者贡献如此优秀的工作，我复现代码时遇到了如题目所述的问题，请问我应该如何解决？

**Comment by sbysbysbys** [comment]
This is normal. For each segmented layer, the color values start from 0 and increment upwards (maximum of 255). This can be difficult for the human eye to distinguish.

**Comment by sbysbysbys** [comment]
It's actually very dark gray.

**Comment by Gmonster-24** [comment]
But the .json files of outputs are also empty, is that normal?

**Comment by sbysbysbys** [comment]
The .json files should be like: [{"id": 1, "category_id": 0, "area": 28823}, {"id": 2, "category_id": 9, "area": 28377}, {"id": 3, "category_id": 52, "area": 75}, {"id": 4, "category_id": 100, "area": 607272}, {"id": 5, "category_id": 105, "area": 23677}, {"id": 6, "category_id": 119, "area": 648026}, {"id": 7, "category_id": 123, "area": 127}, {"id": 8, "category_id": 126, "area": 28}, {"id": 9, "category_id": 142, "area": 5704}, {"id": 10, "category_id": 166, "area": 3994}, {"id": 11, "category_id": 173, "area": 93897}]
That's a weird problem. Could you please print panoptic_seg, segments_info, fin, fout in UOV/ov_segment/fc-clip/demo/superpixel_generation.py line 63 for me, thanks.
You can also uncomment lines 60-61 to visualize the segmentation results and check if there are any problems.

**Comment by Gmonster-24** [comment]
I will try it and get back to you. Thanks a lot!

**Comment by Gmonster-24** [comment]
It becomes normal. I am not sure why the JSON files were empty in the past. Anyway, thanks; the issue is resolved.

**Comment by sbysbysbys** [comment]
Congrats! If you encounter any other issues, please let me know.
