### ISSUE TITLE
Can't find superpixel_generation.py in ov_segment/CAT-Seg or ov_segment/FC-CLIP.

### ISSUE THREAD

**Issue by Agito555** [sbysbysbys/UOV#3]
Hi, thanks for your great job.
I want to generate superpixels using fc-clip. I follow the guide to run corresponding code, but find that there is no superpixel_generation.py in FC-CLIP.
Do I misunderstand or miss something?

**Comment by sbysbysbys** [comment]
It's in demo/ folder, please run "python demo/superpixel_generation.py".  Thanks for pointing out my problem.

**Comment by Agito555** [comment]
Thanks for you quick response :)
